#!/usr/bin/env bash
set -x

source /common.sh
install_chroot_fail_on_error_trap

# prevent any installed services from automatically starting
echo exit 101 > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d

apt-get -y --force-yes install xinit xserver-xorg x11-xserver-utils oracle-java8-jdk fswebcam librxtx-java hostapd isc-dhcp-server bind9 bind9utils dnsutils avahi-daemon libavahi-compat-libdnssd1 dos2unix

#apt-get remove -y --purge aptitude aptitude-common g++ g++-4.9 gcc gcc-4.9 gdb gdbserver luajit perl perl-modules python-rpi.gpio bluez bluez-firmware geoip-database libc-dev-bin libfreetype6-dev samba-common libdrm-radeon1 libdrm-amdgpu1 libdrm-freedreno1 libdrm-nouveau2 xserver-xorg-input-synaptics xserver-xorg-input-wacom manpages manpages-dev

apt-get -y --force-yes upgrade
apt-get autoremove -y
apt-get -y clean

rm -r /usr/sbin/policy-rc.d
rm -rf /opt/*

echo "start_x=0" >> /boot/config.txt
echo "gpu_mem=64" >> /boot/config.txt
echo "disable_overscan=1" >> /boot/config.txt
echo "framebuffer_depth=24" >> /boot/config.txt
echo "framebuffer_ignore_alpha=1" >> /boot/config.txt
echo "hdmi_pixel_encoding=2" >> /boot/config.txt


# install config files
unpack /filesystem/root /

update-rc.d -f bind9 remove
update-rc.d -f isc-dhcp-server remove
update-rc.d -f hostapd remove
update-rc.d -f wifi_access_point remove
#update-rc.d wifi_access_point defaults

wget "$OCTOPI_PHOTONIC3D_START_URL"
chmod a+rx start.sh

./start.sh

echo "All installed packages:"
echo "-----------------------"
#dpkg --get-selections | grep -v deinstall
dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n

rm -f `find /var/log -type f`

echo "Large files:"
echo "------------"
find / -type f -print0 | xargs -0 du | sort -n | tail -20 | cut -f2 | xargs -I{} du -sh {}

echo "Large directories:"
echo "------------------"
find / -type d -print0 | xargs -0 du | sort -n | tail -20 | cut -f2 | xargs -I{} du -sh {}

if [ ! -f /usr/bin/X ]; then
    echo "/usr/bin/X not found!"
    exit 1
fi

